/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MetricsResponse struct {
	Total *TotalMetricsModel `json:"total,omitempty"`
	Cpu *MetricsModel `json:"cpu,omitempty"`
	Mem *MetricsModel `json:"mem,omitempty"`
	Network *NetworkMetricsModel `json:"network,omitempty"`
}
