/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SessionRequest struct {
	// The Unique Identifier of the Session
	SessionId string `json:"session_id"`
	// Custom ID if Available
	CustomId string `json:"custom_id,omitempty"`
	// The Name of the App you requested
	App string `json:"app"`
	// The name of the App Version you requested
	Version string `json:"version"`
	// The Name of the App Version you want to deploy, example:    v1.0
	DeploymentRequestId string `json:"deployment_request_id,omitempty"`
}
