/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BulkSessionDelete struct {
	// List of Delete
	Sessions []Delete `json:"sessions"`
	// List of Delete Errors
	Errors []string `json:"errors"`
}
