/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeploymentLocation struct {
	// City of the deployment
	City string `json:"city"`
	// Country of the deployment
	Country string `json:"country"`
	// Continent of the deployment
	Continent string `json:"continent"`
	// Administrative division of the deployment
	AdministrativeDivision string `json:"administrative_division"`
	// Timezone of the deployment
	Timezone string `json:"timezone"`
	// Latitude of the deployment
	Latitude float32 `json:"latitude"`
	// Longitude of the deployment
	Longitude float32 `json:"longitude"`
}
