/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AppVersionProbe struct {
	// Your optimal value for Latency
	OptimalPing int32 `json:"optimal_ping"`
	// Your reject value for Latency
	RejectedPing int32 `json:"rejected_ping"`
}
