/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SessionModel struct {
	// The Name of the App you want to deploy, example:    supermario
	AppName string `json:"app_name"`
	// The Name of the App Version you want to deploy, example:    v1.0
	VersionName string `json:"version_name,omitempty"`
	// The List of IP of your user, Array of String, example:     [\"162.254.103.13\",\"198.12.116.39\", \"162.254.135.39\", \"162.254.129.34\"]
	IpList []string `json:"ip_list,omitempty"`
	// The list of IP of your user with their location (latitude, longitude)
	GeoIpList []GeoIpListModel `json:"geo_ip_list,omitempty"`
	// The request id of your deployment. If specified, the session will link to the deployment
	DeploymentRequestId string `json:"deployment_request_id,omitempty"`
	// If you want to specify a centroid for your session.
	Location *LocationModel `json:"location,omitempty"`
	// If you want your session in a specific city
	City string `json:"city,omitempty"`
	// If you want your session in a specific country
	Country string `json:"country,omitempty"`
	// If you want your session in a specific continent
	Continent string `json:"continent,omitempty"`
	// If you want your session in a specific administrative division
	AdministrativeDivision string `json:"administrative_division,omitempty"`
	// If you want your session in a specific region
	Region string `json:"region,omitempty"`
}
