/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Locations struct {
	Locations []Location `json:"locations,omitempty"`
	// Extra Messages for the query
	Messages []string `json:"messages,omitempty"`
}
