/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeploymentLogs struct {
	// The logs of your deployment
	Logs string `json:"logs"`
	// The encoding of the logs
	Encoding string `json:"encoding"`
}
