/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeployModel struct {
	// The Name of the App you want to deploy
	AppName string `json:"app_name"`
	// The Name of the App Version you want to deploy, if not present, the last version created is picked
	VersionName string `json:"version_name,omitempty"`
	// The List of IP of your user
	IpList []string `json:"ip_list,omitempty"`
	// The list of IP of your user with their location (latitude, longitude)
	GeoIpList []GeoIpListModel `json:"geo_ip_list,omitempty"`
	// A list of deployment variables
	EnvVars []DeployEnvModel `json:"env_vars,omitempty"`
	// If you want to skip the Telemetry and use a geolocations decision only
	SkipTelemetry bool `json:"skip_telemetry,omitempty"`
	// If you want to specify a centroid for your deployment.
	Location *LocationModel `json:"location,omitempty"`
	// If you want to deploy in a specific city
	City string `json:"city,omitempty"`
	// If you want to deploy in a specific country
	Country string `json:"country,omitempty"`
	// If you want to deploy in a specific continent
	Continent string `json:"continent,omitempty"`
	// If you want to deploy in a specific region
	Region string `json:"region,omitempty"`
	// If you want to deploy in a specific administrative division
	AdministrativeDivision string `json:"administrative_division,omitempty"`
	// A web URL. This url will be called with method POST. The deployment status will be send in JSON format
	WebhookUrl string `json:"webhook_url,omitempty"`
	// The list of tags for your deployment
	Tags []string `json:"tags,omitempty"`
	// The container log storage options for the deployment
	ContainerLogStorage *ContainerLogStorageModel `json:"container_log_storage,omitempty"`
}
