/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MetricsModel struct {
	Labels []string `json:"labels,omitempty"`
	Datasets []float32 `json:"datasets,omitempty"`
	Timestamps []string `json:"timestamps,omitempty"`
}
