/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AppVersionUpdateSessionConfig struct {
	// The kind of session to create. If 'Default' if chosen, the application will be handled like a normal application.
	Kind string `json:"kind,omitempty"`
	// The number of game slots on each deployment of this app version.
	Sockets int32 `json:"sockets,omitempty"`
	// If a deployment should be made autonomously if there is not enough sockets open on a new session.
	Autodeploy bool `json:"autodeploy,omitempty"`
	// The number of minutes a deployment of this app version can spend with no session connected before being terminated.
	EmptyTtl int32 `json:"empty_ttl,omitempty"`
}
