/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AppVersionPort struct {
	// The Port to Expose your service
	Port int32 `json:"port"`
	// The Protocol 'TCP' or 'UDP'
	Protocol string `json:"protocol"`
	// If the port must be verified by our port validations
	ToCheck bool `json:"to_check,omitempty"`
}
