/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Delete struct {
	// A message depending of the request termination
	Message string `json:"message"`
	// The Unique Identifier of the Session
	SessionId string `json:"session_id"`
	// Custom ID if Available
	CustomId string `json:"custom_id,omitempty"`
}
