/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Request struct {
	// The Unique Identifier of the request
	RequestId string `json:"request_id"`
	// The URL to connect to the instance
	RequestDns string `json:"request_dns"`
	// The Name of the App you requested
	RequestApp string `json:"request_app"`
	// The name of the App Version you requested
	RequestVersion string `json:"request_version"`
	// How Many Users your request contain
	RequestUserCount int32 `json:"request_user_count"`
	// The city where the deployment is located
	City string `json:"city,omitempty"`
	// The country where the deployment is located
	Country string `json:"country,omitempty"`
	// The continent where the deployment is located
	Continent string `json:"continent,omitempty"`
	// The administrative division where the deployment is located
	AdministrativeDivision string `json:"administrative_division,omitempty"`
	// List of tags associated with the deployment
	Tags []string `json:"tags,omitempty"`
	// The container log storage options for the deployment
	ContainerLogStorage *ContainerLogStorageModel `json:"container_log_storage"`
}
