/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AppVersionEnv struct {
	// The Key where the Environment Variable will be set
	Key string `json:"key"`
	// The Value to retrieve at the Key
	Value string `json:"value"`
	// This will encrypt the value in our database, won't be readable by external source
	IsSecret bool `json:"is_secret,omitempty"`
}
