/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type StaticSitesList struct {
	Sites []StaticSites `json:"sites,omitempty"`
	// Total of Sites
	TotalCount int32 `json:"total_count,omitempty"`
}
