/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Deployment struct {
	// Unique UUID
	RequestId string `json:"request_id"`
	// The public IP
	PublicIp string `json:"public_ip"`
	// Current status of Deployment
	Status string `json:"status"`
	// if the deployment is ready
	Ready bool `json:"ready"`
	// if the deployment ACL is active
	WhitelistingActive bool `json:"whitelisting_active"`
	// 
	Fqdn string `json:"fqdn"`
	Ports map[string]PortMapping `json:"ports,omitempty"`
	// Location related information
	Location *DeploymentLocation `json:"location,omitempty"`
	// List of tags associated with the deployment
	Tags []string `json:"tags,omitempty"`
	// The Capacity of the Deployment
	Sockets int32 `json:"sockets,omitempty"`
	// The Capacity Usage of the Deployment
	SocketsUsage int32 `json:"sockets_usage,omitempty"`
}
