/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Pagination struct {
	// Current page number
	Number int32 `json:"number,omitempty"`
	// Next page number
	NextPageNumber int32 `json:"next_page_number,omitempty"`
	// Previous page number
	PreviousPageNumber int32 `json:"previous_page_number,omitempty"`
	Paginator *Paginator `json:"paginator,omitempty"`
	// If there is a next page
	HasNext bool `json:"has_next,omitempty"`
	// If there is a previous page
	HasPrevious bool `json:"has_previous,omitempty"`
}
