/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Location struct {
	// City Name
	City string `json:"city"`
	// Continent Name
	Continent string `json:"continent"`
	// Country name
	Country string `json:"country"`
	// Timezone name
	Timezone string `json:"timezone"`
	// Administrative Division
	AdministrativeDivision string `json:"administrative_division"`
	// The Latitude in decimal
	Latitude float32 `json:"latitude"`
	// The Longitude in decimal
	Longitude float32 `json:"longitude"`
}
