/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type StaticSites struct {
	// The URL to bind to
	Url string `json:"url"`
	// Public IP of the Site
	PublicIp string `json:"public_ip"`
	// Port to Bind to
	Port float32 `json:"port"`
	// Latitude of the Site
	Latitude float32 `json:"latitude"`
	// Longitude of the Site
	Longitude float32 `json:"longitude"`
	// City of the Site
	City string `json:"city"`
}
