/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PortMapping struct {
	// The Port to Connect from Internet
	External int32 `json:"external,omitempty"`
	// The internal Port of the Container
	Internal int32 `json:"internal,omitempty"`
	// The Protocol (i.e. 'TCP')
	Protocol string `json:"protocol,omitempty"`
}
