/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Deployments struct {
	// List of Active Deployments
	Data []Deployment `json:"data,omitempty"`
	// Total Objects in the Database
	TotalCount int32 `json:"total_count,omitempty"`
	// Pagination Object
	Pagination *Pagination `json:"pagination,omitempty"`
	// Extra Messages for the query
	Message []string `json:"message,omitempty"`
}
