/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Sessions struct {
	// List of Active Sessions
	Data []SessionContext `json:"data,omitempty"`
	// Total Session in the Database
	TotalCount int32 `json:"total_count,omitempty"`
	// Pagination Object
	Pagination *Pagination `json:"pagination,omitempty"`
}
