/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeployEnvModel struct {
	// The Key to retrieve the value in your instance
	Key string `json:"key"`
	// The value to set in your instance
	Value string `json:"value"`
	// If set to true, the value will be encrypted during the process of deployment
	IsHidden bool `json:"is_hidden,omitempty"`
}
