/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SessionUser struct {
	// Ip of the user connected to the Session
	Ip string `json:"ip"`
	// Latitude
	Latitude float32 `json:"latitude,omitempty"`
	// Longitude
	Longitude float32 `json:"longitude,omitempty"`
}
