/*
 * Codema
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.41.174.post.dev2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApplicationPatch struct {
	// Application name
	Name string `json:"name,omitempty"`
	// If the application can be deployed
	IsActive bool `json:"is_active,omitempty"`
	// Image base64 string
	Image string `json:"image,omitempty"`
}
